### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1

### ISSUE THREAD

**Issue by dpvball** [microsoft/vscode-js-debug-companion#12]
Started receiving this error yesterday. Was working fine before this. I have tried to check if I can do javascript debugging from either chrome or edge and both give me this error now. 

![image](https://user-images.githubusercontent.com/69223794/113351602-f4fd1d80-92ef-11eb-8869-987a98b79660.png)

I'm current running Windows 10 64bit on AMD. VS Code and WSL 2 instance of Ubuntu. I reset my entire operating system (Win 10) and started from scratch and was still receiving this error. Regardless of if I attach or launch with either chrome/edge it gives me this error. On launch it will just close down the browser automatically. 

after 10 seconds VS code will give the timed out waiting for browser connection error.
![image](https://user-images.githubusercontent.com/69223794/113351872-56bd8780-92f0-11eb-8484-8c8bdcf0a427.png)

I have tried restarting, resetting the pc, etc. The chrome debugger configuration is correctly set to --remote-debugging-port=9222 with my launch.json
`        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "url": "http://localhost:1337",
            "port": 9222,
            "webRoot": "${workspaceFolder}"
        }
`

I even upgraded to insider builds beta channel to see if possibly there was something that broke.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/120227
