### ISSUE TITLE
Missing Icon for RUN 

### ISSUE THREAD

**Issue by FDiskas** [microsoft/vscode-js-debug-companion#2]
Issue Type: <b>Bug</b>

missing icon:
![image](https://user-images.githubusercontent.com/468006/83126475-85bc0900-a0e1-11ea-9087-8aa3bf8ee238.png)

Extension version: 1.0.2
VS Code version: Code - Insiders 1.46.0-insider (1d268b701376470bc638100fbe17d283404ac559, 2020-05-28T08:45:32.560Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 5, 4|
|Memory (System)|16.00GB (2.56GB free)|
|Process Argv|-psn_0_794818|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
You may want to file this issue on https://github.com/microsoft/vscode
