### ISSUE TITLE
Can be used with flutter web?

### ISSUE THREAD

**Issue by pedro-gilmora** [microsoft/vscode-js-debug-companion#21]

**Comment by pedro-gilmora** [comment]
I mean for Codespaces, so sorry, I forgot to specify

**Comment by connor4312** [comment]
I don't know much on the Flutter side.

This extension works if you connect to a codespace from the Codespaces extension in VS Code desktop, but not via web (unless you set up RDP or something). We need to be able to launch the browser in debug mode, which we cannot do as an ordinary webpage.

**Comment by pedro-gilmora** [comment]
Flutter needs a Chrome installation to raise its debugger port. I thought this extension could achieve remotely. It might be a good support. Something like to send and event to VSCode local to raise local Chrome and stablish a connection. I guess it might need to me registrable as a flutter device, providing an ID to be selected as a runnable device. I guess you got my point.

**Comment by connor4312** [comment]
> Something like to send and event to VSCode local to raise local Chrome and stablish a connection

That's pretty much how it works when you debug while connected to codespaces from a local VS Code install. There's a "[companion extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-companion)" that runs on the local side for this purpose. But again this is not something than a 'random webpage' can do.
