### ISSUE TITLE
Google Chrome cannot read and write to the data directory: [object Promise]

### ISSUE THREAD

**Issue by lucono** [microsoft/vscode-js-debug-companion#7]
My existing launch configuration suddenly started launching Chrome with flag `--user-data-dir=[object Promise]`, resulting in Chrome showing a dialog at launch with message "__Google Chrome cannot read and write to the data directory: [object Promise]__", which I've now traced to [this change](https://github.com/microsoft/vscode-js-debug-companion/commit/25cd7b0e6dd27a209166e664dff3c5a064954ee6#diff-3439ebd0aad3b843c888483e4e69fc0fR69).

Here's my launch config:
```json
{
    "name": "Test with Chrome",
    "type": "pwa-chrome",
    "request": "launch",
    "browserLaunchLocation": "ui",
    "url": "http://localhost:8080"
}
```

**Comment by connor4312** [comment]
Oof, thanks for the issue. I'm not sure why this didn't show up in my testing.
